name: Lipo-Extra
version: '1.0.0'
main: dev.lipoteam.lipoExtra.LipoExtra
api-version: '1.21'
authors: [ Nopal, Nxsrulswd ]
description: Extra Plugin made by Lipo Team
softdepend: [Jobs, CMILib, NoteBlockAPI, AdvancedChests, ProCosmetics, GriefDefender, CoreProtect]
depend: [CMI, CoinsEngine, ProCosmetics]
